config/routes.rb
# typed: strict
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#home'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'

  resources :users, only: %i[new create]

  resources :whiskeys
  get 'search', to: 'whiskeys#search'
  # resources :search
end

app/models/application_record.rb
# frozen_string_literal: true

# typed: strong
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# typed: strict
# frozen_string_literal: true

# a user of our application who represents an account
class User < ApplicationRecord
  has_secure_password
  has_many :whiskeys
end

app/models/whiskey.rb
# frozen_string_literal: true

# typed: true

# a single whiskey rating record
class Whiskey < ApplicationRecord
  extend T::Sig

  include ::WhiskeysConcern

  belongs_to :user
end

app/controllers/application_controller.rb
# typed: true

# frozen_string_literal: true

# the controller that is the base for all controllers in the application
class ApplicationController < ActionController::Base
  extend T::Sig

  skip_before_action :verify_authenticity_token
  before_action :init_presenter, :authorize

  def init_presenter
    @presenter = ApplicationPresenter.new(self)
  end

  sig { returns(T.nilable(User)) }
  def current_user
    User.find_by(id: session[:user_id])
  end

  sig { returns(T::Boolean) }
  def logged_in?
    !current_user.nil?
  end

  private

  def authorize
    redirect_to '/' unless logged_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# typed: true

# handles user sessions
class SessionsController < ApplicationController
  extend T::Sig

  skip_before_action :authorize, only: %i[home new create welcome]

  def create
    @user = User.find_by(username: params[:username])

    if @user && T.unsafe(@user).authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_url
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  def login; end

  def home
    redirect_to '/welcome' unless logged_in?
  end

  def welcome; end
end

app/controllers/users_controller.rb
# typed: true
# frozen_string_literal: true

# manage users of our system
class UsersController < ApplicationController
  extend T::Sig

  skip_before_action :authorize, only: %i[new create]

  def create
    @user = User.create(user_params)

    session[:user_id] = @user.id

    redirect_to '/'
  end
  
  private
  def user_params
    params
        .require_typed(:user, TA[ActionController::Parameters].new)
        .permit(:username, :password)
  end
end

app/controllers/whiskeys_controller.rb
# frozen_string_literal: true

# typed: true

# Manage whiskey ratings.
# Note: assumes that the ApplicationController.current_user is valid
class WhiskeysController < ApplicationController
  extend T::Sig

  # before_action :set_whiskey, only: %i[show edit update destroy]

  # GET /whiskeys
  # GET /whiskeys.json
  def index
    @whiskeys = Whiskey.where(user_id: T.must(current_user).id)
  end

  # GET /whiskeys/1
  # GET /whiskeys/1.json
  def show
    # set_whiskey
    @whiskey = find_whiskey
  end

  # GET /whiskeys/new
  def new
    @whiskey = Whiskey.new(user_id: T.must(current_user).id)
  end

  # GET /whiskeys/1/edit
  def edit; end

  # POST /whiskeys
  # POST /whiskeys.json
  def create
    @whiskey = Whiskey.new(whiskey_params)
    validate_whiskey

    respond_to do |format|
      if @whiskey.save
        format.html { redirect_to '/', notice: 'Whiskey was successfully created.' }
        format.json { render :show, status: :created, location: @whiskey }
      else
        format.html { render :new }
        format.json { render json: @whiskey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whiskeys/1
  # PATCH/PUT /whiskeys/1.json
  def update
    respond_to do |format|
      if @whiskey.update(whiskey_params)
        format.html { redirect_to @whiskey, notice: 'Whiskey was successfully updated.' }
        format.json { render :show, status: :ok, location: @whiskey }
      else
        format.html { render :edit }
        format.json { render json: @whiskey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /whiskeys/1
  # DELETE /whiskeys/1.json
  def destroy
    @whiskey.destroy
    respond_to do |format|
      format.html { redirect_to whiskeys_url, notice: 'Whiskey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # find all whiskeys given some parameters
  # GET /whiskeys/search.json?contains=&taste=&color=&smokey=
  sig { void }
  def search
    @whiskeys = search_whiskey(
      T.must(current_user),
      contains: params[:contains] && params[:contains].to_s,
      taste: params[:taste] && params[:taste].to_i,
      color: params[:color] && params[:color].to_i,
      smokey: params[:smokey] && params[:smokey].to_i
    )
  end

  private

  # this method should be a Whiskey concern, but could not get that to work,
  # so it is here for now
  sig do
    params(
      user: User,
      contains: T.nilable(String),
      taste: T.nilable(Integer),
      color: T.nilable(Integer),
      smokey: T.nilable(Integer)
    )
      .returns(T.nilable(Whiskey::ActiveRecord_Relation))
  end
  def search_whiskey(user, contains: nil, taste: nil, color: nil, smokey: nil)
    whiskeys = Whiskey.where user_id: user.id
    whiskeys = whiskeys.where 'LOWER(name) LIKE :name', name: "%#{contains}%" if contains
    whiskeys = whiskeys.where 'rate_taste >= :taste', taste: taste if taste
    whiskeys = whiskeys.where 'rate_color >= :color', color: color if color
    whiskeys = whiskeys.where 'rate_smokey >= :smokey', smokey: smokey if smokey
    whiskeys
  end

  # throw an error if the whiskey_user is not the current_user
  def validate_whiskey
    raise 'Not the logged in user' if @whiskey.user_id != T.must(current_user).id
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_whiskey
    @whiskey = Whiskey.find(params[:id])
  end

  def find_whiskey
    Whiskey.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def whiskey_params
    params
      .require_typed(:whiskey, TA[ActionController::Parameters].new)
      .permit(
        :user_id,
        :name,
        :description,
        :rate_taste,
        :rate_color,
        :rate_smokey
      )
  end
end

app/helpers/application_helper.rb
# typed: strong
module ApplicationHelper
end

app/helpers/page_helper.rb
# typed: strong
module PageHelper
end

app/views/layouts/application.html.slim
doctype html
html(style="height: 100%")
  head
    title Whiskywise
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-suppress-warning': true
  body.font-sans.bg-gray-200(style="height: 100%")

    nav.bg-gray-800.px-12.text-white.flex.justify-between.-ml-3
      = image_tag("logo.png", :alt => "Whiskey Wise")
      .flex.my-auto.text-base.text-gray-400
        - if @presenter.logged_in?
          .mr-5.mt-2.text-lg
            | Welcome
            =< @presenter.current_user.username
          = link_to "Log out", '/logout', class: 'px-3 py-2 rounded-md bg-gray-700'
        - else
          = link_to "Log in", '/login', class: 'px-3 py-2 rounded-md bg-gray-700'
          = link_to "Sign up", '/users/new', class: 'ml-3 px-3 py-2 rounded-md bg-gray-700'

    = yield

app/views/users/new.html.slim
.bg-cover(style="height: 100vh; background-image: url(/assets/bar-glass.jpg);")

  = form_for :user, url: { action: 'create' } do |f|

    .flex.items-center.justify-center.py-16.px-4.sm_px-6.lg_px-8
      .max-w-md.w-full.bg-gray-50.p-6.rounded-lg.shadow-xl.mt-16
        div
          h2.mt-6.text-center.text-3xl.leading-9.font-extrabold.text-gray-900
            |  Get started with your
            br
            | whiskey tasting collection!
          p.my-6.text-center.text-sm.leading-5.text-gray-600
            |  Or 
            a.font-medium.text-indigo-600.hover_text-indigo-500.focus_outline-none.focus_underline.transition.ease-in-out.duration-150[href="#"]
              = link_to 'sign in to your account', '/login'
        div
          .rounded-md.shadow-sm
            div
              = f.text_field :username, { \
                class: 'appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus_outline-none focus_shadow-outline-blue focus_border-blue-300 focus_z-10 sm_text-sm sm_leading-5',
                placeholder: 'Email address',
              }
              = f.password_field :password, { \
                class: 'appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus_outline-none focus_shadow-outline-blue focus_border-blue-300 focus_z-10 sm_text-sm sm_leading-5',
                placeholder: 'Password',
              }
          .mt-10
            = f.submit 'Create my Account', class: 'group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-yellow-400 hover_bg-indigo-500 focus_outline-none focus_border-indigo-700 focus_shadow-outline-indigo active_bg-indigo-700 transition duration-150 ease-in-out'

app/views/whiskeys/_form.html.slim
/ = form_with(model: whiskey, local: true) do |form|
/   - if whiskey.errors.any?
/     #error_explanation
/       h2
/         = pluralize(whiskey.errors.count, "error")
/         | prohibited this whiskey from being saved:
/       ul
/         - whiskey.errors.full_messages.each do |message|
/           li= message
/   .field
/     = form.label :user_id
/     = form.text_field :user_id
/   .field
/     = form.label :name
/     = form.text_field :name
/   .field
/     = form.label :description
/     = form.text_area :description
/   .field
/     = form.label :rate_taste
/     = form.number_field :rate_taste
/   .field
/     = form.label :rate_color
/     = form.number_field :rate_color
/   .field
/     = form.label :rate_smokey
/     = form.number_field :rate_smokey
/   .actions
/     = form.submit

.leading-loose
  = form_with(model: whiskey, local: true, class: 'max-w-xl m-4 p-10 bg-white rounded shadow-xl') do |form|
    - if whiskey.errors.any?
      #error_explanation
        h2
          = pluralize(whiskey.errors.count, "error")
          | prohibited this whiskey from being saved:
        ul
          - whiskey.errors.full_messages.each do |message|
            li= message

    p.text-gray-800.font-medium
      | New Whiskey
    = form.hidden_field :user_id
    .mt-2
      = form.label :name, class: 'label block text-sm text-gray-00'
      = form.text_field :name, class: 'w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
    .mt-2
      = form.label :description, class: 'label block text-sm text-gray-00'
      = form.text_area :description, placeholder: 'How did you like this whiskey?', class: 'w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
    .mt-2
      = form.label :rate_taste, class: 'label block text-sm text-gray-00'
      = form.number_field :rate_taste, placeholder: 'rate 1 to 5', class: 'w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
    .mt-2
      = form.label :rate_color, class: 'label block text-sm text-gray-00'
      = form.number_field :rate_color, placeholder: 'rate 1 to 5', class: 'w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
    .mt-2
      = form.label :rate_smokey, class: 'label block text-sm text-gray-00'
      = form.number_field :rate_smokey, placeholder: 'rate 1 to 5', class: 'w-full px-5 py-1 text-gray-700 bg-gray-200 rounded'
    .mt-4
      = form.submit 'Add this Whiskey', class: 'px-4 py-1 text-white font-light tracking-wider bg-gray-900 rounded'
      / button.px-4.py-1.text-white.font-light.tracking-wider.bg-gray-900.rounded[type="submit"]
      /   | $3.00

app/views/whiskeys/edit.html.slim
h1 Editing Whiskey
= render 'form', whiskey: @whiskey
=> link_to 'Show', @whiskey
| |
=< link_to 'Back', whiskeys_path

app/views/whiskeys/index.html.slim
p#notice= notice
h1 Whiskeys
table
  thead
    tr
      th User
      th Name
      th Description
      th Rate taste
      th Rate color
      th Rate smokey
      th colspan="3" 
  tbody
    - @whiskeys.each do |whiskey|
      tr
        td= whiskey.user_id
        td= whiskey.name
        td= whiskey.description
        td= whiskey.rate_taste
        td= whiskey.rate_color
        td= whiskey.rate_smokey
        td= link_to 'Show', whiskey
        td= link_to 'Edit', edit_whiskey_path(whiskey)
        td= link_to 'Destroy', whiskey, method: :delete, data: { confirm: 'Are you sure?' }  
br
= link_to 'New Whiskey', new_whiskey_path

app/views/whiskeys/new.html.slim
.my-20.flex.justify-center
  .w-1of2
    = render 'form', whiskey: @whiskey
/ = link_to 'Back', whiskeys_path

app/views/whiskeys/show.html.slim
p#notice= notice
p
  strong User:
  = @whiskey.user_id
p
  strong Name:
  = @whiskey.name
p
  strong Description:
  = @whiskey.description
p
  strong Rate taste:
  = @whiskey.rate_taste
p
  strong Rate color:
  = @whiskey.rate_color
p
  strong Rate smokey:
  = @whiskey.rate_smokey
=> link_to 'Edit', edit_whiskey_path(@whiskey)
| |
=< link_to 'Back', whiskeys_path